apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:
      containers:
        - name: todobackend
          image: levonmaister/todokube:1.1
          ports:
            - containerPort: 8080
          env:
            - name: GREETING
              value: "Hello from Kubernetes"